<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/DefInjected/**/*.xml key. For each key, resolves the
  English text: the mod ships no Mod/Languages/English (English is supplied by the shipped
  Def's own field), so English is read directly from Mod/Defs and Mod/Patches by dotted path
  against the Def's own XML, mirroring how the game itself falls back. This is why the file
  is built by a script, not by hand: a hand-copy cannot be trusted not to drift from the Defs.

  Original (source-language) text: TheGoofyOne's original Beef Eaters has no non-English
  source (see ATTRIBUTION.md) — Original equals English throughout, stated once here rather
  than on every row.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defTypeHint, $key) {
    # key looks like "DefName.field" or "DefName.tools.left_hoof.label" (spaces became
    # underscores) or "DefName.tools.horn-1.label" (duplicate labels get a -N suffix).
    # ThingDef and PawnKindDef can share the same defName, so the def is looked up by
    # (type, defName), not defName alone - a defName-only lookup can silently grab the
    # wrong node's fields.
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    $cacheKey = "$defTypeHint::$defName"
    if (-not $script:defCache.ContainsKey($cacheKey)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//$defTypeHint[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$cacheKey] = $found
    }
    $node = $script:defCache[$cacheKey]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($null -eq $cur) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
            continue
        }
        # Direct field on the current element (labelMale, description, ...).
        if ($cur.$p) { $cur = $cur.$p; continue }
        # List item, matched the way the game names anonymous DefInjected entries: the
        # segment is the item's own <label> (spaces -> underscores), with a "-N" suffix
        # when several siblings share that label.
        $suffixMatch = [regex]::Match($p, '^(.*)-(\d+)$')
        $index = 0
        $labelWanted = $p -replace '_', ' '
        if ($suffixMatch.Success) {
            $labelWanted = $suffixMatch.Groups[1].Value -replace '_', ' '
            $index = [int]$suffixMatch.Groups[2].Value
        }
        $candidates = @($cur.ChildNodes | Where-Object {
            $_.NodeType -eq 'Element' -and (
                ($_.label -and $_.label -eq $labelWanted) -or ($_.defName -and $_.defName -eq $labelWanted)
            )
        })
        if ($candidates.Count -gt $index) { $cur = $candidates[$index] } else { return $null }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$defsRoot = Join-Path $Root 'Mod/Defs'
$patchesRoot = Join-Path $Root 'Mod/Patches'
$script:defFiles = @()
$script:defFiles += Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
if (Test-Path $patchesRoot) { $script:defFiles += Get-ChildItem $patchesRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName } }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``Tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** TheGoofyOne's original Beef Eaters has no")
[void]$out.AppendLine("non-English source (see ATTRIBUTION.md); the mod ships no ``Mod/Languages/English`` either, so")
[void]$out.AppendLine("both Original and English are read directly from the shipped Def (``Mod/Defs``, ``Mod/Patches``).")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree, no French text changed since.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }
    $defTypeHint = ($rel -split '/')[1] # DefInjected/<DefType>/File.xml

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = Resolve-DefField $defTypeHint $key
        $en = $orig
        if ($null -eq $orig) { $orig = '*(not found - check by hand)*' }
        if ($null -eq $en) { $en = '*(not found - check by hand)*' }
        $flag = if ($fr -match '\?\?\?|TODO' -or ($fr -match '\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? [^:]*:[^:]*:[^}]*\}')) { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
